namespace OSFRS.Backend.Helpers.Usage;

/// <summary>
/// Defines all valid usage event types generated by the system.
/// </summary>
/// <remarks>
/// These constants provide a single source of truth for event classification.
/// Any event logged into the usage tracking system must use one of these values.
/// The <see cref="All"/> array is used for validation, filtering, or analytics.
/// </remarks>
public class UsageEventTypes
{
    /// <summary>Event triggered when a user creates a reservation.</summary>
    public const string ReservationCreated = "ReservationCreated";

    /// <summary>Event triggered when a reservation is updated by its owner.</summary>
    public const string ReservationUpdated = "ReservationUpdated";

    /// <summary>Event triggered when a reservation is cancelled by its owner.</summary>
    public const string ReservationCancelled = "ReservationCancelled";

    /// <summary>Event triggered when a reservation is deleted (admin only).</summary>
    public const string ReservationDeleted = "ReservationDeleted";

    /// <summary>Event triggered when an admin updates an existing reservation.</summary>
    public const string ReservationAdminUpdated = "ReservationAdminUpdated";


    /// <summary>Event triggered when a new facility is created.</summary>
    public const string FacilityCreated = "FacilityCreated";

    /// <summary>Event triggered when an existing facility is updated.</summary>
    public const string FacilityUpdated = "FacilityUpdated";

    /// <summary>Event triggered when a facility is deleted.</summary>
    public const string FacilityDeleted = "FacilityDeleted";

    /// <summary>Event triggered when a facility's availability value is changed.</summary>
    public const string FacilityAvailabilityChanged = "FacilityAvailabilityChanged";


    /// <summary>Event triggered when a new maintenance record is scheduled.</summary>
    public const string MaintenanceScheduled = "MaintenanceScheduled";

    /// <summary>Event triggered when an existing maintenance record is updated.</summary>
    public const string MaintenanceUpdated = "MaintenanceUpdated";

    /// <summary>Event triggered when a maintenance record is deleted.</summary>
    public const string MaintenanceDeleted = "MaintenanceDeleted";


    /// <summary>Event triggered when the system synchronizes facility statuses.</summary>
    public const string StatusSyncRun = "StatusSyncRun";

    /// <summary>Event triggered after daily/monthly aggregation is computed.</summary>
    public const string AggregateComputed = "AggregateComputed";


    /// <summary>
    /// Contains all valid usage event types.
    /// </summary>
    /// <remarks>
    /// Useful for validation (e.g., verifying incoming analytics queries),
    /// and for ensuring consistency across logging, reporting, and filtering.
    /// </remarks>
    public static readonly string[] All =
    {
        ReservationCreated,
        ReservationUpdated,
        ReservationCancelled,
        ReservationDeleted,
        ReservationAdminUpdated,
        FacilityCreated,
        FacilityUpdated,
        FacilityDeleted,
        FacilityAvailabilityChanged,
        MaintenanceScheduled,
        MaintenanceUpdated,
        MaintenanceDeleted,
        StatusSyncRun,
        AggregateComputed
    };
}